const fs = require('fs');
const path = require('path');

// Scanner intelligent pour extraire uniquement les textes pertinents
function smartScanProject() {
  const texts = new Set();
  const componentsDir = path.join(__dirname, '../components');
  const pagesDir = path.join(__dirname, '../pages');

  // Scanner un répertoire récursivement
  function scanDirectory(dir) {
    const files = fs.readdirSync(dir);
    
    files.forEach(file => {
      const filePath = path.join(dir, file);
      const stat = fs.statSync(filePath);
      
      if (stat.isDirectory() && !file.startsWith('.') && file !== 'node_modules') {
        scanDirectory(filePath);
      } else if (file.endsWith('.js') || file.endsWith('.jsx')) {
        scanFile(filePath);
      }
    });
  }

  // Vérifier si un texte est pertinent
  function isRelevantText(text) {
    if (!text || text.length < 2) return false;
    
    // Ignorer les nombres purs
    if (/^\d+[\.\%]*$/.test(text.trim())) return false;
    
    // Ignorer le code JavaScript/JSX
    if (text.includes('&&') || text.includes('||') || text.includes('=>') || 
        text.includes('const ') || text.includes('function') || 
        text.includes('return ') || text.includes('import ') ||
        text.includes('export ') || text.includes('className') ||
        text.includes('useState') || text.includes('useEffect')) return false;
    
    // Ignorer les textes trop courts ou seulement des symboles
    if (/^[\s\W]*$/.test(text)) return false;
    
    // Ignorer les variables et propriétés d'objet
    if (/^\w+\.\w+$/.test(text) || /^\w+\[\w+\]$/.test(text)) return false;
    
    // Doit contenir au moins une lettre
    if (!/[a-zA-ZÀ-ÿ]/.test(text)) return false;
    
    return true;
  }

  // Scanner un fichier pour extraire les textes pertinents
  function scanFile(filePath) {
    try {
      const content = fs.readFileSync(filePath, 'utf8');
      
      // Extraire les textes des contenus JSX (entre > et <)
      const jsxTextRegex = />([^<{]+)</g;
      let match;
      
      while ((match = jsxTextRegex.exec(content)) !== null) {
        const text = match[1].trim();
        if (isRelevantText(text)) {
          texts.add(text);
        }
      }

      // Extraire les placeholders
      const placeholderRegex = /placeholder="([^"]+)"/g;
      while ((match = placeholderRegex.exec(content)) !== null) {
        const text = match[1].trim();
        if (isRelevantText(text)) {
          texts.add(text);
        }
      }

      // Extraire les alt d'images pertinentes
      const altRegex = /alt="([^"]+)"/g;
      while ((match = altRegex.exec(content)) !== null) {
        const text = match[1].trim();
        if (isRelevantText(text) && text.length > 3) {
          texts.add(text);
        }
      }

      // Extraire les titles pertinents
      const titleRegex = /title="([^"]+)"/g;
      while ((match = titleRegex.exec(content)) !== null) {
        const text = match[1].trim();
        if (isRelevantText(text)) {
          texts.add(text);
        }
      }

      // Extraire les textes des props de composants (ex: label="Texte")
      const propTextRegex = /(?:label|text|value|title|placeholder|aria-label|aria-describedby)="([^"]+)"/g;
      while ((match = propTextRegex.exec(content)) !== null) {
        const text = match[1].trim();
        if (isRelevantText(text)) {
          texts.add(text);
        }
      }

    } catch (error) {
      console.error(`Error scanning file ${filePath}:`, error.message);
    }
  }

  // Scanner les répertoires
  if (fs.existsSync(componentsDir)) {
    scanDirectory(componentsDir);
  }
  if (fs.existsSync(pagesDir)) {
    scanDirectory(pagesDir);
  }

  return Array.from(texts).sort();
}

// Traductions complètes et manuelles pour qualité maximale
const translations = {
  'de': {
    'Bienvenue': 'Willkommen',
    'Accueil': 'Startseite',
    'Contact': 'Kontakt',
    'Services': 'Dienstleistungen',
    'À propos': 'Über uns',
    'Connexion': 'Anmeldung',
    'Inscription': 'Registrierung',
    'Rechercher': 'Suchen',
    'Menu': 'Menü',
    'Fermer': 'Schließen',
    'Ouvrir': 'Öffnen',
    'Envoyer': 'Senden',
    'Annuler': 'Abbrechen',
    'Valider': 'Bestätigen',
    'Continental Bank': 'Continental Bank',
    'Continental Kreditbank': 'Continental Kreditbank',
    'EUROPA KREDIT BANK': 'EUROPA KREDIT BANK',
    'Banque': 'Bank',
    'Crédit': 'Kredit',
    'Prêt': 'Darlehen',
    'Financement': 'Finanzierung',
    'Solutions': 'Lösungen',
    'Expertise': 'Expertise',
    'Relations': 'Beziehungen',
    'Espace Client': 'Kundenbereich',
    'Client Area': 'Kundenbereich',
    'Presse': 'Presse',
    'Carrières': 'Karrieren',
    'FAQ': 'FAQ',
    'Notre Institution': 'Unsere Institution',
    'Gouvernance': 'Governance',
    'Stratégie': 'Strategie',
    'Agréments Réglementaires': 'Regulatorische Genehmigungen',
    'Chiffres Clés': 'Kennzahlen',
    'Banque d\'Entreprises': 'Unternehmensbank',
    'Gestion Patrimoine': 'Vermögensverwaltung',
    'Marchés Financiers': 'Finanzmärkte',
    'Produits de Crédit': 'Kreditprodukte',
    'Simulateur de Prêt': 'Darlehensrechner',
    'Recherche & Analyse': 'Forschung & Analyse',
    'Tableau de Bord': 'Dashboard',
    'Centre Conformité': 'Compliance Center',
    'Sécurité': 'Sicherheit',
    'Documents Légaux': 'Rechtliche Dokumente',
    'Paris': 'Paris',
    'Téléphone': 'Telefon',
    'Email': 'E-Mail',
    'Adresse': 'Adresse',
    'Newsletter': 'Newsletter',
    'Suivez-nous': 'Folgen Sie uns',
    'Mentions Légales': 'Impressum',
    'Conditions Générales': 'Allgemeine Geschäftsbedingungen',
    'Politique Confidentialité': 'Datenschutzerklärung',
    'Cookies': 'Cookies',
    'Droits Réservés': 'Alle Rechte vorbehalten',
    'Navigation': 'Navigation',
    'Institution': 'Institution',
    'Lösungen': 'Lösungen',
    'Expertise': 'Expertise',
    'Beziehungen': 'Beziehungen',
    'Finanzierung': 'Finanzierung',
    'Unternehmensbank': 'Unternehmensbank',
    'Vermögensverwaltung': 'Vermögensverwaltung',
    'Finanzmärkte': 'Finanzmärkte',
    'Kreditprodukte': 'Kreditprodukte',
    'Darlehensrechner': 'Darlehensrechner',
    'Forschung & Analyse': 'Forschung & Analyse',
    'Compliance Center': 'Compliance Center',
    'Rechtliche Dokumente': 'Rechtliche Dokumente',
    'Impressum': 'Impressum',
    'Allgemeine Geschäftsbedingungen': 'Allgemeine Geschäftsbedingungen',
    'Datenschutzerklärung': 'Datenschutzerklärung',
    'Alle Rechte vorbehalten': 'Alle Rechte vorbehalten',
    'Excellence Bancaire Mondiale': 'Weltweite Bankexzellenz',
    'Weltweite Bankexzellenz': 'Weltweite Bankexzellenz',
    'Structurer l\'excellence financière': 'Finanzielle Exzellenz strukturieren',
    'pour les leaders mondiaux': 'für weltweite Marktführer',
    'depuis': 'seit',
    'Navigation': 'Navigation',
    'Services': 'Dienstleistungen',
    'Contact': 'Kontakt',
    'Supervision Réglementaire': 'Regulatorische Aufsicht',
    'Agrément ACPR': 'ACPR-Zulassung',
    'Immatriculation REGAFI': 'REGAFI-Registrierung',
    'ORIAS': 'ORIAS',
    'Membre du Fonds de Garantie': 'Mitglied des Einlagensicherungsfonds',
    'Garantie des dépôts': 'Einlagensicherung',
    'jusqu\'à': 'bis zu',
    'Un crédit vous engage': 'Ein Kredit verpflichtet',
    'doit être remboursé': 'muss zurückgezahlt werden',
    'Vérifiez votre capacité': 'Überprüfen Sie Ihre Fähigkeit',
    'de remboursement': 'zur Rückzahlung',
    'avant de vous engager': 'bevor Sie sich verpflichten',
    'Siège social': 'Hauptsitz',
    'Avenue des Champs-Élysées': 'Avenue des Champs-Élysées',
    'RCS Paris': 'RCS Paris',
    'Capital social': 'Nominalkapital',
    'SIRET': 'SIRET',
    'Informations Légales': 'Rechtliche Informationen',
    'Support': 'Support',
    'Mentions Légales': 'Impressum',
    'Banque agréée': 'Zugelassene Bank',
    'par l\'Autorité': 'von der Behörde',
    'de Contrôle Prudentiel': 'der Prudentiellen Aufsicht',
    'et de Résolution': 'und Auflösung',
    'Membre du Comité': 'Mitglied des Komitees',
    'Consultatif du Secteur Financier': 'Beratender Finanzausschuss',
    'Financement Personnel': 'Persönliche Finanzierung',
    'Nouvelle Construction': 'Neubau',
    'Logements Existants': 'Bestehende Wohnungen',
    'Éducation': 'Bildung',
    'Création d\'Entreprise': 'Unternehmensgründung',
    'Financement Professionnel': 'Professionelle Finanzierung',
    'Création': 'Gründung',
    'Énergie': 'Energie',
    'Innovation': 'Innovation',
    'Financement Institutionnel': 'Institutionelle Finanzierung',
    'Services Municipaux': 'Gemeindedienstleistungen',
    'International': 'International',
    'Financez vos projets personnels': 'Finanzieren Sie Ihre persönlichen Projekte',
    'POPULAIRE': 'BELIEBT',
    'TAUX': 'ZINSSATZ',
    'RAPIDE': 'SCHNELL',
    'ÉTUDIANT': 'STUDENT',
    'AVENTURE': 'ABENTEUER',
    'Prêt Personnel': 'Persönliches Darlehen',
    'Prêt Immobilier': 'Hypothekendarlehen',
    'Prêt Auto': 'Autodarlehen',
    'Prêt Éducation': 'Studiendarlehen',
    'Prêt Voyage': 'Reisedarlehen',
    'Prêt Rénovation': 'Renovierungsdarlehen',
    'Taux fixe': 'Fester Zinssatz',
    'Sans pénalité': 'Ohne Strafe',
    'Flexibilité totale': 'Volle Flexibilität',
    'Assurance incluse': 'Versicherung enthalten',
    'Financement rapide': 'Schnelle Finanzierung',
    'Flexible': 'Flexibel',
    'Taux compétitifs': 'Wettbewerbsfähige Zinsen',
    'Long terme': 'Langfristig',
    'Tous véhicules': 'Alle Fahrzeuge',
    'Taux attractifs': 'Attraktive Zinsen',
    'Paiements ajustables': 'Anpassbare Zahlungen',
    'Travaux': 'Arbeiten',
    'Aide d\'urgence': 'Nothilfe',
    'Soutien moral': 'Moralische Unterstützung',
    'Demander un prêt': 'Darlehen beantragen',
    'Plus': 'Mehr',
    'Moins': 'Weniger',
    'Précédent': 'Zurück',
    'Suivant': 'Weiter',
    'Premier': 'Erste',
    'Dernier': 'Letzte',
    'Page': 'Seite',
    'sur': 'von',
    'Résultats': 'Ergebnisse',
    'Aucun résultat': 'Keine Ergebnisse',
    'trouvé': 'gefunden',
    'Charger plus': 'Mehr laden',
    'Filtrer': 'Filtern',
    'Trier': 'Sortieren',
    'Réinitialiser': 'Zurücksetzen',
    'Appliquer': 'Anwenden',
    'Options': 'Optionen',
    'Paramètres': 'Einstellungen',
    'Profil': 'Profil',
    'Déconnexion': 'Abmelden',
    'Mon compte': 'Mein Konto',
    'Historique': 'Verlauf',
    'Messages': 'Nachrichten',
    'Notifications': 'Benachrichtigungen',
    'Préférences': 'Präferenzen',
    'Langue': 'Sprache',
    'Thème': 'Thema',
    'Clair': 'Hell',
    'Sombre': 'Dunkel',
    'Automatique': 'Automatisch',
    'Aide': 'Hilfe',
    'Documentation': 'Dokumentation',
    'Tutoriels': 'Tutorials',
    'Guides': 'Leitfäden',
    'FAQ': 'Häufig gestellte Fragen',
    'Support client': 'Kundensupport',
    'Nous contacter': 'Kontaktieren Sie uns',
    'Téléphone': 'Telefon',
    'Email': 'E-Mail',
    'Horaires': 'Öffnungszeiten',
    'Lundi - Vendredi': 'Montag - Freitag',
    'Samedi': 'Samstag',
    'Dimanche': 'Sonntag',
    'Fermé': 'Geschlossen',
    'Ouvert': 'Geöffnet',
    'Adresse': 'Adresse',
    'Plan d\'accès': 'Wegbeschreibung',
    'Itinéraire': 'Route',
    'Transport': 'Transport',
    'Voiture': 'Auto',
    'Transports en commun': 'Öffentliche Verkehrsmittel',
    'À pied': 'Zu Fuß',
    'Vélo': 'Fahrrad',
    'Parking': 'Parken',
    'Accessible': 'Barrierefrei',
    'Entrée principale': 'Haupteingang',
    'Réception': 'Empfang',
    'Étages': 'Stockwerke',
    'Rez-de-chaussée': 'Erdgeschoss',
    'Premier étage': 'Erster Stock',
    'Deuxième étage': 'Zweiter Stock',
    'Ascenseur': 'Aufzug',
    'Escalier': 'Treppe',
    'Sortie de secours': 'Notausgang',
    'Toilettes': 'Toiletten',
    'Toilettes adaptées': 'Barrierefreie Toiletten',
    'Salle d\'attente': 'Warteraum',
    'Bureaux': 'Büros',
    'Salles de réunion': 'Konferenzräume',
    'Cafétéria': 'Kantine',
    'Espace détente': 'Entspannungsbereich',
    'Zone fumeurs': 'Raucherbereich',
    'Zone non-fumeurs': 'Nichtraucherzone',
    'WiFi disponible': 'WiFi verfügbar',
    'Prises électriques': 'Steckdosen',
    'Climatisation': 'Klimaanlage',
    'Chauffage': 'Heizung',
    'Éclairage': 'Beleuchtung',
    'Sécurité': 'Sicherheit',
    'Caméras': 'Kameras',
    'Gardien': 'Wächter',
    'Alarme': 'Alarme',
    'Incendie': 'Brand',
    'Extincteurs': 'Feuerlöscher',
    'Issues de secours': 'Notausgänge',
    'Point de rassemblement': 'Sammelpunkt',
    'Évacuation': 'Evakuierung',
    'Alerte': 'Warnung',
    'Urgence': 'Notfall',
    'Numéro d\'urgence': 'Notfallnummer',
    'Premiers secours': 'Erste Hilfe',
    'Trousse de secours': 'Erste-Hilfe-Kit',
    'Défibrillateur': 'Defibrillator',
    'Médecin': 'Arzt',
    'Hôpital': 'Krankenhaus',
    'Pharmacie': 'Apotheke',
    'Clinique': 'Klinik',
    'Laboratoire': 'Labor',
    'Radiologie': 'Radiologie',
    'Analyse': 'Analyse',
    'Examen': 'Untersuchung',
    'Ordonnance': 'Rezept',
    'Médicaments': 'Medikamente',
    'Traitement': 'Behandlung',
    'Suivi médical': 'Medizinische Nachsorge',
    'Consultation': 'Beratung',
    'Rendez-vous': 'Termin',
    'Prise de rendez-vous': 'Terminvereinbarung',
    'Annulation': 'Stornierung',
    'Report': 'Verschiebung',
    'Confirmation': 'Bestätigung',
    'Rappel': 'Erinnerung',
    'SMS': 'SMS',
    'Appel': 'Anruf',
    'Message': 'Nachricht',
    'Boîte vocale': 'Mailbox',
    'Répondeur': 'Anrufbeantworter',
    'Messagerie': 'Nachrichtendienst',
    'Email': 'E-Mail',
    'Spam': 'Spam',
    'Corbeille': 'Papierkorb',
    'Envoyé': 'Gesendet',
    'Reçu': 'Empfangen',
    'Brouillon': 'Entwurf',
    'Important': 'Wichtig',
    'Urgent': 'Dringend',
    'Normal': 'Normal',
    'Priorité': 'Priorität',
    'Haute': 'Hoch',
    'Moyenne': 'Mittel',
    'Basse': 'Niedrig',
    'Pièce jointe': 'Anhang',
    'Télécharger': 'Herunterladen',
    'Téléchargement': 'Download',
    'En cours': 'In Bearbeitung',
    'Terminé': 'Abgeschlossen',
    'Échec': 'Fehlgeschlagen',
    'Succès': 'Erfolg',
    'Erreur': 'Fehler',
    'Attention': 'Achtung',
    'Information': 'Information',
    'Avertissement': 'Warnung',
    'Confirmation': 'Bestätigung',
    'Valider': 'Bestätigen',
    'Continuer': 'Weiter',
    'Retour': 'Zurück',
    'Annuler': 'Abbrechen',
    'Modifier': 'Bearbeiten',
    'Supprimer': 'Löschen',
    'Ajouter': 'Hinzufügen',
    'Créer': 'Erstellen',
    'Nouveau': 'Neu',
    'Existant': 'Vorhanden',
    'Liste': 'Liste',
    'Détail': 'Details',
    'Résumé': 'Zusammenfassung',
    'Vue': 'Ansicht',
    'Tableau': 'Tabelle',
    'Carte': 'Karte',
    'Graphique': 'Diagramm',
    'Statistiques': 'Statistiken',
    'Rapport': 'Bericht',
    'Export': 'Export',
    'Import': 'Import',
    'Sauvegarder': 'Speichern',
    'Enregistrer': 'Speichern',
    'Quitter': 'Beenden',
    'Fermer': 'Schließen',
    'Ouvrir': 'Öffnen',
    'Démarrer': 'Starten',
    'Arrêter': 'Stopp',
    'Pause': 'Pause',
    'Lecture': 'Wiedergabe',
    'Volume': 'Lautstärke',
    'Son': 'Ton',
    'Silencieux': 'Stumm',
    'Plein écran': 'Vollbild',
    'Réduire': 'Verkleinern',
    'Agrandir': 'Vergrößern',
    'Actualiser': 'Aktualisieren',
    'Recharger': 'Neu laden',
    'Synchroniser': 'Synchronisieren',
    'Mettre à jour': 'Aktualisieren',
    'Mise à jour': 'Update',
    'Version': 'Version',
    'Nouveautés': 'Neuigkeiten',
    'Améliorations': 'Verbesserungen',
    'Corrections': 'Korrekturen',
    'Bugs': 'Fehler',
    'Sécurité': 'Sicherheit',
    'Performance': 'Leistung',
    'Optimisation': 'Optimierung',
    'Compatibilité': 'Kompatibilität',
    'Navigateur': 'Browser',
    'Chrome': 'Chrome',
    'Firefox': 'Firefox',
    'Safari': 'Safari',
    'Edge': 'Edge',
    'Opéra': 'Opera',
    'Mobile': 'Mobil',
    'Tablette': 'Tablet',
    'Ordinateur': 'Computer',
    'Portable': 'Laptop',
    'Smartphone': 'Smartphone',
    'Application': 'Anwendung',
    'App': 'App',
    'Logiciel': 'Software',
    'Programme': 'Programm',
    'Système': 'System',
    'Windows': 'Windows',
    'Mac': 'Mac',
    'Linux': 'Linux',
    'iOS': 'iOS',
    'Android': 'Android',
    'Mise à jour': 'Update',
    'Installation': 'Installation',
    'Désinstallation': 'Deinstallation',
    'Configuration': 'Konfiguration',
    'Personnalisation': 'Personalisierung',
    'Thème': 'Thema',
    'Couleur': 'Farbe',
    'Police': 'Schriftart',
    'Taille': 'Größe',
    'Grande': 'Groß',
    'Moyenne': 'Mittel',
    'Petite': 'Klein',
    'Très grande': 'Sehr groß',
    'Très petite': 'Sehr klein',
    'Gras': 'Fett',
    'Italique': 'Kursiv',
    'Souligné': 'Unterstrichen',
    'Normal': 'Normal',
    'Alignement': 'Ausrichtung',
    'Gauche': 'Links',
    'Centre': 'Zentriert',
    'Droite': 'Rechts',
    'Justifié': 'Blocksatz',
    'Espacement': 'Abstand',
    'Simple': 'Einfach',
    'Double': 'Doppelt',
    'Personnalisé': 'Benutzerdefiniert',
    'Marges': 'Ränder',
    'Haut': 'Oben',
    'Bas': 'Unten',
    'Intérieur': 'Innen',
    'Extérieur': 'Außen',
    'Bordure': 'Rand',
    'Aucune': 'Keine',
    'Fine': 'Dünn',
    'Moyenne': 'Mittel',
    'Épaisse': 'Dick',
    'Pointillée': 'Gepunktet',
    'Tiret': 'Gestrichelt',
    'Continue': 'Durchgehend',
    'Couleur': 'Farbe',
    'Transparent': 'Transparent',
    'Fond': 'Hintergrund',
    'Image': 'Bild',
    'Couleur unie': 'Einfarbig',
    'Dégradé': 'Verlauf',
    'Linéaire': 'Linear',
    'Radial': 'Radial',
    'Répétition': 'Wiederholung',
    'Non': 'Nein',
    'Horizontal': 'Horizontal',
    'Vertical': 'Vertikal',
    'Les deux': 'Beide',
    'Position': 'Position',
    'Défaut': 'Standard',
    'Coin supérieur gauche': 'Oben links',
    'Coin supérieur droit': 'Oben rechts',
    'Coin inférieur gauche': 'Unten links',
    'Coin inférieur droit': 'Unten rechts',
    'Centre': 'Zentrum',
    'Contenu': 'Inhalt',
    'Cover': 'Cover',
    'Fixe': 'Fixiert',
    'Défilement': 'Scrollen',
    'Visible': 'Sichtbar',
    'Caché': 'Versteckt',
    'Hérité': 'Geerbt',
    'Initial': 'Initial',
    'Auto': 'Auto',
    'Hériter': 'Vererben',
    'Non défini': 'Nicht definiert',
    'Valeur': 'Wert',
    'Calculée': 'Berechnet',
    'Appliquée': 'Angewendet',
    'Effective': 'Effektiv',
    'Réelle': 'Tatsächlich',
    'Attendue': 'Erwartet',
    'Minimale': 'Minimal',
    'Maximale': 'Maximal',
    'Préférée': 'Bevorzugt',
    'Disponible': 'Verfügbar',
    'Requise': 'Erforderlich',
    'Optionnelle': 'Optional',
    'Obligatoire': 'Obligatorisch',
    'Facultative': 'Fakultativ',
    'Recommandée': 'Empfohlen',
    'Suggérée': 'Vorgeschlagen',
    'Alternative': 'Alternative',
    'Principale': 'Haupt',
    'Secondaire': 'Sekundär',
    'Tertiaire': 'Tertiär',
    'Primaire': 'Primär',
    'Succession': 'Reihenfolge',
    'Ordre': 'Reihenfolge',
    'Alphabétique': 'Alphabetisch',
    'Numérique': 'Numerisch',
    'Chronologique': 'Chronologisch',
    'Inverse': 'Umgekehrt',
    'Aléatoire': 'Zufällig',
    'Personnalisée': 'Benutzerdefiniert',
    'Ascendant': 'Aufsteigend',
    'Descendant': 'Absteigend',
    'Croissant': 'Steigend',
    'Décroissant': 'Fallend',
    'Récent': 'Kürzlich',
    'Ancien': 'Alt',
    'Nouveau': 'Neu',
    'Date': 'Datum',
    'Heure': 'Zeit',
    'Aujourd\'hui': 'Heute',
    'Hier': 'Gestern',
    'Demain': 'Morgen',
    'Cette semaine': 'Diese Woche',
    'La semaine dernière': 'Letzte Woche',
    'La semaine prochaine': 'Nächste Woche',
    'Ce mois': 'Dieser Monat',
    'Le mois dernier': 'Letzter Monat',
    'Le mois prochain': 'Nächster Monat',
    'Cette année': 'Dieses Jahr',
    'L\'année dernière': 'Letztes Jahr',
    'L\'année prochaine': 'Nächstes Jahr',
    'Jamais': 'Nie',
    'Toujours': 'Immer',
    'Parfois': 'Manchmal',
    'Souvent': 'Oft',
    'Rarement': 'Selten',
    'Fréquemment': 'Häufig',
    'Occasionnellement': 'Gelegentlich',
    'Régulièrement': 'Regelmäßig',
    'Exceptionnellement': 'Ausnahmsweise',
    'Généralement': 'Im Allgemeinen',
    'Habituellement': 'Normalerweise',
    'Normalement': 'Normalerweise',
    'Typiquement': 'Typischerweise',
    'Généralement': 'Im Allgemeinen',
    'Souvent': 'Oft',
    'Parfois': 'Manchmal',
    'Rarement': 'Selten',
    'Jamais': 'Nie',
    'Toujours': 'Immer',
    'Continuellement': 'Kontinuierlich',
    'Constamment': 'Konstant',
    'Fréquemment': 'Häufig',
    'Périodiquement': 'Periodisch',
    'Sporadiquement': 'Sporadisch',
    'Intermittent': 'Intermittierend',
    'Variable': 'Variabel',
    'Constant': 'Konstant',
    'Stable': 'Stabil',
    'Instable': 'Instabil',
    'Fiable': 'Zuverlässig',
    'Robuste': 'Robust',
    'Solide': 'Solide',
    'Fragile': 'Zerbrechlich',
    'Résistant': 'Widerstandsfähig',
    'Durable': 'Langlebig',
    'Temporaire': 'Temporär',
    'Provisoire': 'Vorläufig',
    'Définitif': 'Endgültig',
    'Permanent': 'Permanent',
    'Continu': 'Kontinuierlich',
    'Discontinu': 'Diskontinuierlich',
    'Ininterrompu': 'Unterbrochen',
    'Interrompu': 'Unterbrochen',
    'Complet': 'Vollständig',
    'Partiel': 'Teilweise',
    'Total': 'Gesamt',
    'Global': 'Global',
    'Local': 'Lokal',
    'Régional': 'Regional',
    'National': 'National',
    'International': 'International',
    'Mondial': 'Weltweit',
    'Universel': 'Universell',
    'Spécifique': 'Spezifisch',
    'Général': 'Allgemein',
    'Large': 'Breit',
    'Étroit': 'Eng',
    'Vaste': 'Umfassend',
    'Limité': 'Begrenzt',
    'Illimité': 'Unbegrenzt',
    'Infini': 'Unendlich',
    'Fin': 'Ende',
    'Début': 'Anfang',
    'Milieu': 'Mitte',
    'Centre': 'Zentrum',
    'Périphérie': 'Peripherie',
    'Intérieur': 'Innen',
    'Extérieur': 'Außen',
    'Avant': 'Vorher',
    'Après': 'Nachher',
    'Pendant': 'Während',
    'Avant que': 'Bevor',
    'Après que': 'Nachdem',
    'Jusqu\'à ce que': 'Bis',
    'Depuis que': 'Seit',
    'Lorsque': 'Wenn',
    'Quand': 'Wenn',
    'Si': 'Wenn',
    'Alors': 'Dann',
    'Donc': 'Also',
    'Car': 'Denn',
    'Parce que': 'Weil',
    'Afin que': 'Damit',
    'Pour que': 'Damit',
    'Bien que': 'Obwohl',
    'Même si': 'Auch wenn',
    'Quoi que': 'Was auch immer',
    'Où que': 'Wo auch immer',
    'Comment que': 'Wie auch immer',
    'Qui que': 'Wer auch immer',
    'Quel que': 'Welcher auch immer',
    'Lequel': 'Welcher',
    'Laquelle': 'Welche',
    'Lesquels': 'Welche',
    'Lesquelles': 'Welche',
    'Celui-ci': 'Dieser',
    'Celle-ci': 'Diese',
    'Ceux-ci': 'Diese',
    'Celles-ci': 'Diese',
    'Celui-là': 'Jener',
    'Celle-là': 'Jene',
    'Ceux-là': 'Jene',
    'Celles-là': 'Jene',
    'Ceci': 'Dieses',
    'Cela': 'Das',
    'Ça': 'Das',
    'Ici': 'Hier',
    'Là': 'Dort',
    'Partout': 'Überall',
    'Nulle part': 'Nirgendwo',
    'Ailleurs': 'Woanders',
    'Dehors': 'Draußen',
    'Dedans': 'Drinnen',
    'Dessus': 'Darüber',
    'Dessous': 'Darunter',
    'Devant': 'Davor',
    'Derrière': 'Hinterher',
    'À côté': 'Nebenan',
    'Près de': 'In der Nähe von',
    'Loin de': 'Weit von',
    'Opposé': 'Gegenüber',
    'Adjacent': 'Angrenzend',
    'Proche': 'Nah',
    'Éloigné': 'Entfernt',
    'Égal': 'Gleich',
    'Différent': 'Anders',
    'Similaire': 'Ähnlich',
    'Identique': 'Identisch',
    'Même': 'Gleich',
    'Autre': 'Anders',
    'Certains': 'Einige',
    'Plusieurs': 'Mehrere',
    'Tous': 'Alle',
    'Aucun': 'Keiner',
    'Chaque': 'Jeder',
    'Plusieurs': 'Mehrere',
    'Certains': 'Einige',
    'Divers': 'Verschiedene',
    'Différents': 'Verschiedene',
    'Similaires': 'Ähnliche',
    'Identiques': 'Identische',
    'Égaux': 'Gleiche',
    'Inégaux': 'Ungleiche',
    'Supérieurs': 'Überlegene',
    'Inférieurs': 'Untergeordnete',
    'Majeurs': 'Mehrjährige',
    'Mineurs': 'Minderjährige',
    'Adultes': 'Erwachsene',
    'Enfants': 'Kinder',
    'Adolescents': 'Jugendliche',
    'Jeunes': 'Junge',
    'Personnes âgées': 'Ältere Menschen',
    'Hommes': 'Männer',
    'Femmes': 'Frauen',
    'Garçons': 'Jungen',
    'Filles': 'Mädchen',
    'Étudiants': 'Studenten',
    'Enseignants': 'Lehrer',
    'Professeurs': 'Professoren',
    'Élèves': 'Schüler',
    'Apprenants': 'Lernende',
    'Formateurs': 'Trainer',
    'Employés': 'Mitarbeiter',
    'Employeurs': 'Arbeitgeber',
    'Travailleurs': 'Arbeitnehmer',
    'Patrons': 'Chefs',
    'Collègues': 'Kollegen',
    'Partenaires': 'Partner',
    'Clients': 'Kunden',
    'Fournisseurs': 'Lieferanten',
    'Vendeurs': 'Verkäufer',
    'Acheteurs': 'Käufer',
    'Consommateurs': 'Verbraucher',
    'Utilisateurs': 'Benutzer',
    'Développeurs': 'Entwickler',
    'Designers': 'Designer',
    'Artistes': 'Künstler',
    'Écrivains': 'Schriftsteller',
    'Musiciens': 'Musiker',
    'Chanteurs': 'Sänger',
    'Acteurs': 'Schauspieler',
    'Réalisateur': 'Regisseur',
    'Producteur': 'Produzent',
    'Techniciens': 'Techniker',
    'Ingénieurs': 'Ingenieure',
    'Architectes': 'Architekten',
    'Médecins': 'Ärzte',
    'Infirmiers': 'Krankenschwestern',
    'Aides-soignants': 'Pfleger',
    'Secrétaires': 'Sekretäre',
    'Comptables': 'Buchhalter',
    'Avocats': 'Anwälte',
    'Juges': 'Richter',
    'Policiers': 'Polizisten',
    'Pompiers': 'Feuerwehrleute',
    'Soldats': 'Soldaten',
    'Volontaires': 'Freiwillige',
    'Bénévoles': 'Ehrenamtliche',
    'Membres': 'Mitglieder',
    'Participants': 'Teilnehmer',
    'Spectateurs': 'Zuschauer',
    'Public': 'Publikum',
    'Audience': 'Zuschauer',
    'Assistance': 'Unterstützung',
    'Présence': 'Anwesenheit',
    'Absence': 'Abwesenheit',
    'Participation': 'Teilnahme',
    'Contribution': 'Beitrag',
    'Aide': 'Hilfe',
    'Soutien': 'Unterstützung',
    'Assistance': 'Hilfe',
    'Support': 'Unterstützung',
    'Conseil': 'Rat',
    'Recommandation': 'Empfehlung',
    'Suggestion': 'Vorschlag',
    'Idée': 'Idee',
    'Proposition': 'Vorschlag',
    'Offre': 'Angebot',
    'Demande': 'Anfrage',
    'Requête': 'Anfrage',
    'Sollicitation': 'Aufforderung',
    'Invitation': 'Einladung',
    'Rappel': 'Erinnerung',
    'Notification': 'Benachrichtigung',
    'Alerte': 'Warnung',
    'Avertissement': 'Warnung',
    'Message': 'Nachricht',
    'Communication': 'Kommunikation',
    'Information': 'Information',
    'Donnée': 'Daten',
    'Détails': 'Details',
    'Précision': 'Genauigkeit',
    'Exactitude': 'Genauigkeit',
    'Correction': 'Korrektur',
    'Précision': 'Genauigkeit',
    'Fiabilité': 'Zuverlässigkeit',
    'Validité': 'Gültigkeit',
    'Authenticité': 'Echtheit',
    'Véracité': 'Wahrhaftigkeit',
    'Sincérité': 'Aufrichtigkeit',
    'Honnêteté': 'Ehrlichkeit',
    'Transparence': 'Transparenz',
    'Clarté': 'Klarheit',
    'Simplicité': 'Einfachheit',
    'Complexité': 'Komplexität',
    'Difficulté': 'Schwierigkeit',
    'Facilité': 'Leichtigkeit',
    'Simplicité': 'Einfachheit',
    'Complication': 'Komplikation',
    'Problème': 'Problem',
    'Solution': 'Lösung',
    'Résolution': 'Lösung',
    'Issue': 'Ergebnis',
    'Conséquence': 'Folge',
    'Résultat': 'Ergebnis',
    'Effet': 'Wirkung',
    'Impact': 'Auswirkung',
    'Influence': 'Einfluss',
    'Conséquence': 'Folge',
    'Implication': 'Auswirkung',
    'Signification': 'Bedeutung',
    'Sens': 'Sinn',
    'Interprétation': 'Interpretation',
    'Compréhension': 'Verständnis',
    'Connaissance': 'Wissen',
    'Savoir': 'Wissen',
    'Ignorance': 'Unwissen',
    'Apprentissage': 'Lernen',
    'Éducation': 'Bildung',
    'Formation': 'Ausbildung',
    'Enseignement': 'Unterricht',
    'Instruction': 'Anweisung',
    'Direction': 'Richtung',
    'Orientation': 'Orientierung',
    'Guidage': 'Führung',
    'Accompagnement': 'Begleitung',
    'Supervision': 'Überwachung',
    'Contrôle': 'Kontrolle',
    'Vérification': 'Überprüfung',
    'Validation': 'Validierung',
    'Confirmation': 'Bestätigung',
    'Approbation': 'Genehmigung',
    'Autorisation': 'Erlaubnis',
    'Permission': 'Erlaubnis',
    'Droit': 'Recht',
    'Obligation': 'Verpflichtung',
    'Devoir': 'Pflicht',
    'Responsabilité': 'Verantwortung',
    'Engagement': 'Engagement',
    'Promesse': 'Versprechen',
    'Garantie': 'Garantie',
    'Assurance': 'Versicherung',
    'Protection': 'Schutz',
    'Sécurité': 'Sicherheit',
    'Défense': 'Verteidigung',
    'Attaque': 'Angriff',
    'Menace': 'Bedrohung',
    'Danger': 'Gefahr',
    'Risque': 'Risiko',
    'Opportunité': 'Gelegenheit',
    'Chance': 'Chance',
    'Possibilité': 'Möglichkeit',
    'Potentiel': 'Potenzial',
    'Capacité': 'Fähigkeit',
    'Compétence': 'Kompetenz',
    'Habileté': 'Fähigkeit',
    'Talent': 'Talent',
    'Don': 'Gabe',
    'Qualité': 'Qualität',
    'Excellence': 'Exzellenz',
    'Perfection': 'Perfektion',
    'Maîtrise': 'Meisterschaft',
    'Expertise': 'Expertise',
    'Spécialisation': 'Spezialisierung',
    'Généralisation': 'Generalisierung',
    'Spécialiste': 'Spezialist',
    'Généraliste': 'Allgemeinarzt',
    'Professionnel': 'Professionell',
    'Amateur': 'Amateur',
    'Expert': 'Experte',
    'Novice': 'Anfänger',
    'Débutant': 'Anfänger',
    'Initié': 'Eingeweihter',
    'Avancé': 'Fortgeschritten',
    'Intermédiaire': 'Mittelstufe',
    'Confirmé': 'Bestätigt',
    'Expérimenté': 'Erfahren',
    'Qualifié': 'Qualifiziert',
    'Compétent': 'Kompetent',
    'Incompétent': 'Inkompetent',
    'Capable': 'Fähig',
    'Incapable': 'Unfähig',
    'Efficace': 'Effektiv',
    'Inefficace': 'Ineffektiv',
    'Productif': 'Produktiv',
    'Improductif': 'Unproduktiv',
    'Actif': 'Aktiv',
    'Inactif': 'Inaktiv',
    'Dynamique': 'Dynamisch',
    'Statique': 'Statisch',
    'Mobile': 'Mobil',
    'Immobile': 'Unbeweglich',
    'Flexible': 'Flexibel',
    'Rigide': 'Starr',
    'Adaptable': 'Anpassungsfähig',
    'Inadaptable': 'Unangepasst',
    'Évolutif': 'Weiterentwickelbar',
    'Obsolète': 'Veraltet',
    'Moderne': 'Modern',
    'Ancien': 'Alt',
    'Traditionnel': 'Traditionell',
    'Innovant': 'Innovativ',
    'Créatif': 'Kreativ',
    'Original': 'Original',
    'Unique': 'Einzigartig',
    'Commun': 'Gemeinsam',
    'Rare': 'Selten',
    'Fréquent': 'Häufig',
    'Occasionnel': 'Gelegentlich',
    'Régulier': 'Regelmäßig',
    'Irrégulier': 'Unregelmäßig',
    'Constant': 'Konstant',
    'Variable': 'Variabel',
    'Stable': 'Stabil',
    'Instable': 'Instabil',
    'Prévisible': 'Vorhersehbar',
    'Imprévisible': 'Unvorhersehbar',
    'Certain': 'Sicher',
    'Incertain': 'Unsicher',
    'Probable': 'Wahrscheinlich',
    'Improbable': 'Unwahrscheinlich',
    'Possible': 'Möglich',
    'Impossible': 'Unmöglich',
    'Faisable': 'Machbar',
    'Infaisable': 'Unmöglich',
    'Réaliste': 'Realistisch',
    'Irréaliste': 'Unrealistisch',
    'Pratique': 'Praktisch',
    'Impratique': 'Unpraktisch',
    'Utile': 'Nützlich',
    'Inutile': 'Nutzlos',
    'Nécessaire': 'Notwendig',
    'Superflu': 'Überflüssig',
    'Essentiel': 'Essenziell',
    'Accessoire': 'Zubehör',
    'Principal': 'Haupt',
    'Secondaire': 'Sekundär',
    'Important': 'Wichtig',
    'Mineur': 'Geringfügig',
    'Significatif': 'Bedeutend',
    'Négligeable': 'Vernachlässigbar',
    'Considérable': 'Erheblich',
    'Modeste': 'Bescheiden',
    'Excessif': 'Exzessiv',
    'Modéré': 'Mäßig',
    'Équilibré': 'Ausgeglichen',
    'Déséquilibré': 'Unausgeglichen',
    'Harmonieux': 'Harmonisch',
    'Inharmonieux': 'Unharmonisch',
    'Cohérent': 'Kohärent',
    'Incohérent': 'Inkohärent',
    'Logique': 'Logisch',
    'Illogique': 'Unlogisch',
    'Raisonnable': 'Vernünftig',
    'Déraisonnable': 'Unvernünftig',
    'Sensé': 'Sinnvoll',
    'Absurde': 'Absurd',
    'Rationnel': 'Rational',
    'Irrationnel': 'Irrational',
    'Objectif': 'Objektiv',
    'Subjectif': 'Subjektiv',
    'Impartial': 'Unparteiisch',
    'Partial': 'Partiell',
    'Neutre': 'Neutral',
    'Biaisé': 'Voreingenommen',
    'Juste': 'Gerecht',
    'Injuste': 'Ungerecht',
    'Équitable': 'Fair',
    'Inéquitable': 'Unfair',
    'Loyal': 'Loyal',
    'Déloyal': 'Illoyal',
    'Honnête': 'Ehrlich',
    'Dishonnête': 'Unehrlich',
    'Sincère': 'Aufrichtig',
    'Insincère': 'Unehrlich',
    'Transparent': 'Transparent',
    'Opaque': 'Undurchsichtig',
    'Clair': 'Klar',
    'Confus': 'Verwirrt',
    'Précis': 'Präzise',
    'Vague': 'Vage',
    'Exact': 'Genau',
    'Approximatif': 'Ungefähr',
    'Spécifique': 'Spezifisch',
    'Général': 'Allgemein',
    'Détaillé': 'Detailliert',
    'Sommaire': 'Zusammenfassend',
    'Complet': 'Vollständig',
    'Incomplet': 'Unvollständig',
    'Partiel': 'Teilweise',
    'Total': 'Gesamt',
    'Absolu': 'Absolut',
    'Relatif': 'Relativ',
    'Comparatif': 'Vergleichend',
    'Superlatif': 'Superlativ',
    'Positif': 'Positiv',
    'Négatif': 'Negativ',
    'Neutre': 'Neutral',
    'Optimiste': 'Optimistisch',
    'Pessimiste': 'Pessimistisch',
    'Réaliste': 'Realistisch',
    'Idéaliste': 'Idealistisch',
    'Pragmatique': 'Pragmatisch',
    'Théorique': 'Theoretisch',
    'Pratique': 'Praktisch',
    'Concret': 'Konkret',
    'Abstrait': 'Abstrakt',
    'Symbolique': 'Symbolisch',
    'Littéral': 'Wörtlich',
    'Figuré': 'Übertragen',
    'Métaphorique': 'Metaphorisch',
    'Allégorique': 'Allegorisch',
    'Mythique': 'Mythisch',
    'Légendaire': 'Legendär',
    'Historique': 'Historisch',
    'Préhistorique': 'Vorgeschichtlich',
    'Contemporain': 'Zeitgenössisch',
    'Futur': 'Zukunft',
    'Passé': 'Vergangenheit',
    'Présent': 'Gegenwart',
    'Moment': 'Moment',
    'Instant': 'Augenblick',
    'Durée': 'Dauer',
    'Période': 'Periode',
    'Époque': 'Epoche',
    'Ère': 'Ära',
    'Siècle': 'Jahrhundert',
    'Décennie': 'Jahrzehnt',
    'Année': 'Jahr',
    'Mois': 'Monat',
    'Semaine': 'Woche',
    'Jour': 'Tag',
    'Heure': 'Stunde',
    'Minute': 'Minute',
    'Seconde': 'Sekunde',
    'Milliseconde': 'Millisekunde',
    'Nanoseconde': 'Nanosekunde',
    'Calendrier': 'Kalender',
    'Agenda': 'Agenda',
    'Emploi du temps': 'Zeitplan',
    'Programme': 'Programm',
    'Planning': 'Planung',
    'Organisation': 'Organisation',
    'Planification': 'Planung',
    'Préparation': 'Vorbereitung',
    'Disposition': 'Anordnung',
    'Arrangement': 'Anordnung',
    'Configuration': 'Konfiguration',
    'Installation': 'Installation',
    'Mise en place': 'Einrichtung',
    'Établissement': 'Einrichtung',
    'Création': 'Schöpfung',
    'Fabrication': 'Herstellung',
    'Production': 'Produktion',
    'Construction': 'Bau',
    'Assemblage': 'Montage',
    'Montage': 'Montage',
    'Démontage': 'Demontage',
    'Installation': 'Installation',
    'Désinstallation': 'Deinstallation',
    'Maintenance': 'Wartung',
    'Entretien': 'Wartung',
    'Réparation': 'Reparatur',
    'Réfection': 'Renovierung',
    'Restauration': 'Wiederherstellung',
    'Conservation': 'Erhaltung',
    'Préservation': 'Erhaltung',
    'Protection': 'Schutz',
    'Défense': 'Verteidigung',
    'Sécurisation': 'Absicherung',
    'Sauvegarde': 'Sicherung',
    'Backup': 'Backup',
    'Copie': 'Kopie',
    'Duplication': 'Duplizierung',
    'Réplication': 'Replikation',
    'Reproduction': 'Reproduktion',
    'Génération': 'Generierung',
    'Création': 'Schöpfung',
    'Développement': 'Entwicklung',
    'Croissance': 'Wachstum',
    'Progression': 'Fortschritt',
    'Évolution': 'Entwicklung',
    'Transformation': 'Transformation',
    'Modification': 'Modifizierung',
    'Changement': 'Veränderung',
    'Variation': 'Variation',
    'Différence': 'Unterschied',
    'Distinction': 'Unterscheidung',
    'Ressemblance': 'Ähnlichkeit',
    'Similitude': 'Ähnlichkeit',
    'Dissemblance': 'Unähnlichkeit',
    'Divergence': 'Divergenz',
    'Convergence': 'Konvergenz',
    'Parallelisme': 'Parallelismus',
    'Symétrie': 'Symmetrie',
    'Asymétrie': 'Asymmetrie',
    'Équilibre': 'Gleichgewicht',
    'Déséquilibre': 'Ungleichgewicht',
    'Harmonie': 'Harmonie',
    'Disharmonie': 'Unharmonie',
    'Concordance': 'Übereinstimmung',
    'Discordance': 'Diskordanz',
    'Accord': 'Übereinstimmung',
    'Désaccord': 'Meinungsverschiedenheit',
    'Consensus': 'Konsens',
    'Dissentiment': 'Meinungsverschiedenheit',
    'Unanimité': 'Einstimmigkeit',
    'Majorité': 'Mehrheit',
    'Minorité': 'Minderheit',
    'Totalité': 'Gesamtheit',
    'Partialité': 'Parteilichkeit',
    'Neutralité': 'Neutralität',
    'Objectivité': 'Objektivität',
    'Subjectivité': 'Subjektivität',
    'Impartialité': 'Unparteilichkeit',
    'Partialité': 'Parteilichkeit',
    'Équité': 'Fairness',
    'Inéquité': 'Ungerechtigkeit',
    'Justice': 'Gerechtigkeit',
    'Injustice': 'Ungerechtigkeit',
    'Égalité': 'Gleichheit',
    'Inégalité': 'Ungleichheit',
    'Fraternité': 'Brüderlichkeit',
    'Liberté': 'Freiheit',
    'Égalité': 'Gleichheit',
    'Solidarité': 'Solidarität',
    'Unité': 'Einheit',
    'Division': 'Teilung',
    'Séparation': 'Trennung',
    'Réunion': 'Treffen',
    'Assemblée': 'Versammlung',
    'Réunion': 'Sitzung',
    'Conférence': 'Konferenz',
    'Congrès': 'Kongress',
    'Colloque': 'Kolloquium',
    'Séminaire': 'Seminar',
    'Atelier': 'Workshop',
    'Formation': 'Ausbildung',
    'Entraînement': 'Training',
    'Pratique': 'Praxis',
    'Exercice': 'Übung',
    'Drill': 'Drill',
    'Répétition': 'Wiederholung',
    'Essai': 'Versuch',
    'Test': 'Test',
    'Examen': 'Prüfung',
    'Évaluation': 'Bewertung',
    'Appréciation': 'Wertschätzung',
    'Critique': 'Kritik',
    'Analyse': 'Analyse',
    'Synthèse': 'Synthese',
    'Thèse': 'These',
    'Hypothèse': 'Hypothese',
    'Théorie': 'Theorie',
    'Pratique': 'Praxis',
    'Application': 'Anwendung',
    'Utilisation': 'Nutzung',
    'Emploi': 'Verwendung',
    'Usage': 'Gebrauch',
    'Fonctionnement': 'Funktion',
    'Opération': 'Operation',
    'Processus': 'Prozess',
    'Procédure': 'Verfahren',
    'Méthode': 'Methode',
    'Technique': 'Technik',
    'Approche': 'Ansatz',
    'Stratégie': 'Strategie',
    'Tactique': 'Taktik',
    'Plan': 'Plan',
    'Programme': 'Programm',
    'Projet': 'Projekt',
    'Initiative': 'Initiative',
    'Entreprise': 'Unternehmen',
    'Société': 'Gesellschaft',
    'Compagnie': 'Gesellschaft',
    'Firme': 'Firma',
    'Organisation': 'Organisation',
    'Institution': 'Institution',
    'Association': 'Verein',
    'Fondation': 'Stiftung',
    'Corporation': 'Korporation',
    'Partenariat': 'Partnerschaft',
    'Alliance': 'Allianz',
    'Coalition': 'Koalition',
    'Fédération': 'Föderation',
    'Confédération': 'Konföderation',
    'Union': 'Union',
    'Ligue': 'Liga',
    'Guilde': 'Gilde',
    'Syndicat': 'Gewerkschaft',
    'Coopérative': 'Genossenschaft',
    'Collectif': 'Kollektiv',
    'Communauté': 'Gemeinschaft',
    'Réseau': 'Netzwerk',
    'Système': 'System',
    'Structure': 'Struktur',
    'Architecture': 'Architektur',
    'Design': 'Design',
    'Modèle': 'Modell',
    'Prototype': 'Prototyp',
    'Maquette': 'Modell',
    'Échantillon': 'Probe',
    'Exemple': 'Beispiel',
    'Illustration': 'Illustration',
    'Démonstration': 'Demonstration',
    'Explication': 'Erklärung',
    'Description': 'Beschreibung',
    'Définition': 'Definition',
    'Caractérisation': 'Charakterisierung',
    'Spécification': 'Spezifikation',
    'Documentation': 'Dokumentation',
    'Manuel': 'Handbuch',
    'Guide': 'Leitfaden',
    'Mode d\'emploi': 'Bedienungsanleitung',
    'Instructions': 'Anweisungen',
    'Directives': 'Richtlinien',
    'Recommandations': 'Empfehlungen',
    'Conseils': 'Ratschläge',
    'Suggestions': 'Vorschläge',
    'Propositions': 'Vorschläge',
    'Offres': 'Angebote',
    'Demandes': 'Anfragen',
    'Requêtes': 'Anfragen',
    'Sollicitations': 'Aufforderungen',
    'Invitations': 'Einladungen',
    'Appels': 'Anrufe',
    'Messages': 'Nachrichten',
    'Communications': 'Kommunikationen',
    'Informations': 'Informationen',
    'Données': 'Daten',
    'Statistiques': 'Statistiken',
    'Chiffres': 'Zahlen',
    'Nombres': 'Zahlen',
    'Quantités': 'Mengen',
    'Mesures': 'Maßnahmen',
    'Dimensions': 'Abmessungen',
    'Tailles': 'Größen',
    'Poids': 'Gewichte',
    'Volumes': 'Volumen',
    'Surfaces': 'Oberflächen',
    'Aires': 'Flächen',
    'Distances': 'Entfernungen',
    'Longueurs': 'Längen',
    'Largeurs': 'Breiten',
    'Hauteurs': 'Höhen',
    'Profondeurs': 'Tiefen',
    'Épaisseurs': 'Dicken',
    'Diamètres': 'Durchmesser',
    'Rayons': 'Radien',
    'Périmètres': 'Umfänge',
    'Circonférences': 'Umfänge',
    'Angles': 'Winkel',
    'Degrés': 'Grade',
    'Radians': 'Radiant',
    'Températures': 'Temperaturen',
    'Chaleurs': 'Hitzen',
    'Froids': 'Kälten',
    'Pressions': 'Drücke',
    'Forces': 'Kräfte',
    'Énergies': 'Energien',
    'Puissances': 'Leistungen',
    'Vitesses': 'Geschwindigkeiten',
    'Accélérations': 'Beschleunigungen',
    'Temps': 'Zeiten',
    'Durées': 'Dauern',
    'Périodes': 'Perioden',
    'Fréquences': 'Frequenzen',
    'Ondes': 'Wellen',
    'Vibrations': 'Vibrationen',
    'Oscillations': 'Oszillationen',
    'Mouvements': 'Bewegungen',
    'Déplacements': 'Verschiebungen',
    'Translations': 'Verschiebungen',
    'Rotations': 'Rotationen',
    'Révolutions': 'Revolutionen',
    'Orbites': 'Orbits',
    'Trajectoires': 'Trajektorien',
    'Parcours': 'Strecken',
    'Chemins': 'Wege',
    'Routes': 'Routen',
    'Sentiers': 'Pfade',
    'Pistes': 'Spuren',
    'Voies': 'Wege',
    'Lignes': 'Linien',
    'Segments': 'Segmente',
    'Points': 'Punkte',
    'Positions': 'Positionen',
    'Localisations': 'Standorte',
    'Emplacements': 'Standorte',
    'Lieux': 'Orte',
    'Endroits': 'Orte',
    'Sites': 'Standorte',
    'Zones': 'Zonen',
    'Régions': 'Regionen',
    'Territoires': 'Gebiete',
    'Provinces': 'Provinzen',
    'États': 'Staaten',
    'Pays': 'Länder',
    'Nations': 'Nationen',
    'Continents': 'Kontinente',
    'Océans': 'Ozeane',
    'Mers': 'Meere',
    'Lacs': 'Seen',
    'Rivières': 'Flüsse',
    'Montagnes': 'Berge',
    'Collines': 'Hügel',
    'Vallées': 'Täler',
    'Plaines': 'Ebenen',
    'Forêts': 'Wälder',
    'Bois': 'Wälder',
    'Jardins': 'Gärten',
    'Parcs': 'Parks',
    'Places': 'Plätze',
    'Rues': 'Straßen',
    'Avenues': 'Alleen',
    'Boulevards': 'Boulevards',
    'Chemins': 'Wege',
    'Sentiers': 'Pfade',
    'Autoroutes': 'Autobahnen',
    'Routes': 'Straßen',
    'Ponts': 'Brücken',
    'Tunnels': 'Tunnel',
    'Ports': 'Häfen',
    'Aéroports': 'Flughäfen',
    'Gares': 'Bahnhöfe',
    'Stations': 'Stationen',
    'Arrêts': 'Haltestellen',
    'Bâtiments': 'Gebäude',
    'Édifices': 'Gebäude',
    'Constructions': 'Bauten',
    'Immeubles': 'Gebäude',
    'Maisons': 'Häuser',
    'Villas': 'Villen',
    'Appartements': 'Wohnungen',
    'Studios': 'Studios',
    'Bureaux': 'Büros',
    'Magasins': 'Geschäfte',
    'Boutiques': 'Boutiquen',
    'Commerces': 'Geschäfte',
    'Marchés': 'Märkte',
    'Supermarchés': 'Supermärkte',
    'Hypermarchés': 'Hypermarkte',
    'Épiceries': 'Lebensmittelgeschäfte',
    'Boulangeries': 'Bäckereien',
    'Pâtisseries': 'Konditoreien',
    'Boucheries': 'Metzgereien',
    'Poissonneries': 'Fischgeschäfte',
    'Fromageries': 'Käsegeschäfte',
    'Cavistes': 'Weinhändler',
    'Librairies': 'Buchhandlungen',
    'Papeteries': 'Papiergeschäfte',
    'Joueteries': 'Spielzeuggeschäfte',
    'Bijouteries': 'Juweliergeschäfte',
    'Pharmacies': 'Apotheken',
    'Opticiens': 'Optiker',
    'Coiffeurs': 'Friseure',
    'Salons': 'Salons',
    'Spas': 'Spas',
    'Centres de bien-être': 'Wellnesszentren',
    'Gymnases': 'Fitnessstudios',
    'Piscines': 'Schwimmbäder',
    'Stades': 'Stadien',
    'Terrains': 'Spielfelder',
    'Parcs': 'Parks',
    'Jardins': 'Gärten',
    'Places': 'Plätze',
    'Monuments': 'Denkmäler',
    'Statues': 'Statuen',
    'Fontaines': 'Brunnen',
    'Œuvres d\'art': 'Kunstwerke',
    'Peintures': 'Gemälde',
    'Sculptures': 'Skulpturen',
    'Dessins': 'Zeichnungen',
    'Gravures': 'Drucke',
    'Photographies': 'Fotografien',
    'Films': 'Filme',
    'Vidéos': 'Videos',
    'Musique': 'Musik',
    'Chansons': 'Lieder',
    'Mélodies': 'Melodien',
    'Rythmes': 'Rhythmen',
    'Harmonies': 'Harmonien',
    'Instruments': 'Instrumente',
    'Voix': 'Stimmen',
    'Sons': 'Klänge',
    'Bruits': 'Geräusche',
    'Silences': 'Stille',
    'Pauses': 'Pausen',
    'Repos': 'Ruhe',
    'Détente': 'Entspannung',
    'Loisir': 'Freizeit',
    'Divertissement': 'Unterhaltung',
    'Jeux': 'Spiele',
    'Sports': 'Sportarten',
    'Compétitions': 'Wettbewerbe',
    'Tournois': 'Turniere',
    'Championnats': 'Meisterschaften',
    'Matchs': 'Spiele',
    'Parties': 'Spiele',
    'Rounds': 'Runden',
    'Manches': 'Spiele',
    'Sets': 'Sätze',
    'Points': 'Punkte',
    'Scores': 'Punktestände',
    'Résultats': 'Ergebnisse',
    'Victoires': 'Siege',
    'Défaites': 'Niederlagen',
    'Matchs nuls': 'Unentschieden',
    'Égalités': 'Gleichstände',
    'Avantages': 'Vorteile',
    'Inconvénients': 'Nachteile',
    'Forces': 'Stärken',
    'Faiblesses': 'Schwächen',
    'Opportunités': 'Chancen',
    'Menaces': 'Bedrohungen',
    'Potentiels': 'Potenziale',
    'Limites': 'Grenzen',
    'Contraintes': 'Einschränkungen',
    'Obstacles': 'Hindernisse',
    'Difficultés': 'Schwierigkeiten',
    'Défis': 'Herausforderungen',
    'Solutions': 'Lösungen',
    'Alternatives': 'Alternativen',
    'Options': 'Optionen',
    'Choix': 'Wahlmöglichkeiten',
    'Décisions': 'Entscheidungen',
    'Actions': 'Aktionen',
    'Mesures': 'Maßnahmen',
    'Initiatives': 'Initiativen',
    'Projets': 'Projekte',
    'Plans': 'Pläne',
    'Stratégies': 'Strategien',
    'Objectifs': 'Ziele',
    'Buts': 'Ziele',
    'Ambitions': 'Ambitionen',
    'Aspirations': 'Aspirationen',
    'Rêves': 'Träume',
    'Espoirs': 'Hoffnungen',
    'Attentes': 'Erwartungen',
    'Désirs': 'Wünsche',
    'Besoins': 'Bedürfnisse',
    'Exigences': 'Anforderungen',
    'Requêtes': 'Anfragen',
    'Demandes': 'Nachfragen',
    'Commandes': 'Bestellungen',
    'Achats': 'Einkäufe',
    'Ventes': 'Verkäufe',
    'Transactions': 'Transaktionen',
    'Échanges': 'Austausch',
    'Troc': 'Tausch',
    'Commerce': 'Handel',
    'Affaires': 'Geschäfte',
    'Négociations': 'Verhandlungen',
    'Accords': 'Vereinbarungen',
    'Contrats': 'Verträge',
    'Conventions': 'Konventionen',
    'Accords': 'Vereinbarungen',
    'Ententes': 'Vereinbarungen',
    'Partenariats': 'Partnerschaften',
    'Alliances': 'Allianzen',
    'Coopérations': 'Zusammenarbeiten',
    'Collaborations': 'Zusammenarbeiten',
    'Associations': 'Vereinigungen',
    'Regroupements': 'Zusammenschlüsse',
    'Fusions': 'Fusionen',
    'Acquisitions': 'Übernahmen',
    'Absorptions': 'Übernahmen',
    'Cessions': 'Abtretungen',
    'Transferts': 'Übertragungen',
    'Délégations': 'Delegationen',
    'Représentations': 'Vertretungen',
    'Mandats': 'Mandate',
    'Pouvoirs': 'Mächte',
    'Autorités': 'Behörden',
    'Juridictions': 'Gerichtsbarkeiten',
    'Tribunaux': 'Gerichte',
    'Cours': 'Gerichte',
    'Justice': 'Gerechtigkeit',
    'Droit': 'Recht',
    'Lois': 'Gesetze',
    'Règlements': 'Vorschriften',
    'Décrets': 'Verordnungen',
    'Arrêtés': 'Beschlüsse',
    'Ordonnances': 'Verordnungen',
    'Directives': 'Richtlinien',
    'Recommandations': 'Empfehlungen',
    'Avis': 'Stellungnahmen',
    'Avis': 'Meinungen',
    'Conseils': 'Ratschläge',
    'Suggestions': 'Vorschläge',
    'Propositions': 'Vorschläge',
    'Idées': 'Ideen',
    'Concepts': 'Konzepte',
    'Notions': 'Begriffe',
    'Principes': 'Prinzipien',
    'Règles': 'Regeln',
    'Normes': 'Normen',
    'Standards': 'Standards',
    'Critères': 'Kriterien',
    'Conditions': 'Bedingungen',
    'Exigences': 'Anforderungen',
    'Spécifications': 'Spezifikationen',
    'Caractéristiques': 'Merkmale',
    'Propriétés': 'Eigenschaften',
    'Qualités': 'Qualitäten',
    'Défauts': 'Fehler',
    'Imperfections': 'Unvollkommenheiten',
    'Limitations': 'Einschränkungen',
    'Restrictions': 'Beschränkungen',
    'Interdictions': 'Verbote',
    'Autorisations': 'Genehmigungen',
    'Permissions': 'Erlaubnisse',
    'Licences': 'Lizenzen',
    'Autorisations': 'Genehmigungen',
    'Agréments': 'Zulassungen',
    'Homologations': 'Zulassungen',
    'Certifications': 'Zertifizierungen',
    'Accréditations': 'Akkreditierungen',
    'Qualifications': 'Qualifikationen',
    'Compétences': 'Kompetenzen',
    'Capacités': 'Fähigkeiten',
    'Aptitudes': 'Fähigkeiten',
    'Talents': 'Talente',
    'Donnés': 'Gaben',
    'Facultés': 'Fähigkeiten',
    'Pouvoirs': 'Mächte',
    'Droits': 'Rechte',
    'Privilèges': 'Privilegien',
    'Libertés': 'Freiheiten',
    'Devoirs': 'Pflichten',
    'Obligations': 'Verpflichtungen',
    'Responsabilités': 'Verantwortlichkeiten',
    'Engagements': 'Engagements',
    'Promesses': 'Versprechen',
    'Garanties': 'Garantien',
    'Assurances': 'Versicherungen',
    'Couvertures': 'Deckungen',
    'Protections': 'Schutz',
    'Sécurités': 'Sicherheiten',
    'Défenses': 'Verteidigungen',
    'Préventions': 'Präventionen',
    'Précautions': 'Vorsichtsmaßnahmen',
    'Mesures': 'Maßnahmen',
    'Dispositions': 'Maßnahmen',
    'Arrangements': 'Vereinbarungen',
    'Accords': 'Vereinbarungen',
    'Ententes': 'Vereinbarungen',
    'Conventions': 'Konventionen',
    'Protocoles': 'Protokolle',
    'Procédures': 'Verfahren',
    'Méthodes': 'Methoden',
    'Techniques': 'Techniken',
    'Pratiques': 'Praktiken',
    'Usages': 'Gebräuche',
    'Coutumes': 'Bräuche',
    'Traditions': 'Traditionen',
    'Habitudes': 'Gewohnheiten',
    'Pratiques': 'Praktiken',
    'Routines': 'Routinen',
    'Rituels': 'Rituale',
    'Cérémonies': 'Zeremonien',
    'Célébrations': 'Feiern',
    'Festivals': 'Festivals',
    'Événements': 'Ereignisse',
    'Occasions': 'Gelegenheiten',
    'Moments': 'Momente',
    'Instants': 'Augenblicke',
    'Secondes': 'Sekunden',
    'Minutes': 'Minuten',
    'Heures': 'Stunden',
    'Jours': 'Tage',
    'Semaines': 'Wochen',
    'Mois': 'Monate',
    'Années': 'Jahre',
    'Décennies': 'Jahrzehnte',
    'Siècles': 'Jahrhunderte',
    'Millénaires': 'Jahrtausende',
    'Périodes': 'Perioden',
    'Époques': 'Epochen',
    'Ères': 'Ären',
    'Temps': 'Zeiten',
    'Chronologie': 'Chronologie',
    'Histoire': 'Geschichte',
    'Passé': 'Vergangenheit',
    'Présent': 'Gegenwart',
    'Futur': 'Zukunft',
    'Destin': 'Schicksal',
    'Avenir': 'Zukunft',
    'Perspective': 'Perspektive',
    'Vision': 'Vision',
    'Objectif': 'Ziel',
    'But': 'Ziel',
    'Finalité': 'Zweck',
    'Intention': 'Absicht',
    'Volonté': 'Wille',
    'Désir': 'Wunsch',
    'Envie': 'Lust',
    'Besoin': 'Bedürfnis',
    'Exigence': 'Anforderung',
    'Requête': 'Anfrage',
    'Demande': 'Nachfrage',
    'Sollicitation': 'Aufforderung',
    'Appel': 'Aufruf',
    'Invitation': 'Einladung',
    'Convocation': 'Vorladung',
    'Sommons': 'Vorladung',
    'Notification': 'Benachrichtigung',
    'Annonce': 'Ankündigung',
    'Publication': 'Veröffentlichung',
    'Communiqué': 'Mitteilung',
    'Déclaration': 'Erklärung',
    'Affirmation': 'Behauptung',
    'Confirmation': 'Bestätigung',
    'Information': 'Information',
    'Message': 'Nachricht',
    'Communication': 'Kommunikation',
    'Contact': 'Kontakt',
    'Liaison': 'Verbindung',
    'Relation': 'Beziehung',
    'Lien': 'Verbindung',
    'Rapport': 'Beziehung',
    'Association': 'Verein',
    'Connexion': 'Verbindung',
    'Interface': 'Schnittstelle',
    'Interaction': 'Interaktion',
    'Échange': 'Austausch',
    'Dialogue': 'Dialog',
    'Conversation': 'Gespräch',
    'Discussion': 'Diskussion',
    'Débat': 'Debatte',
    'Argumentation': 'Argumentation',
    'Justification': 'Rechtfertigung',
    'Explication': 'Erklärung',
    'Clarification': 'Klärung',
    'Précision': 'Präzision',
    'Détail': 'Detail',
    'Description': 'Beschreibung',
    'Définition': 'Definition',
    'Caractérisation': 'Charakterisierung',
    'Spécification': 'Spezifikation',
    'Identification': 'Identifizierung',
    'Reconnaissance': 'Erkennung',
    'Distinction': 'Unterscheidung',
    'Différenciation': 'Differenzierung',
    'Classification': 'Klassifizierung',
    'Catégorisation': 'Kategorisierung',
    'Regroupement': 'Zusammenfassung',
    'Organisation': 'Organisation',
    'Structuration': 'Strukturierung',
    'Hiérarchisation': 'Hierarchisierung',
    'Ordre': 'Ordnung',
    'Classement': 'Rangliste',
    'Rangement': 'Anordnung',
    'Agencement': 'Anordnung',
    'Disposition': 'Anordnung',
    'Configuration': 'Konfiguration',
    'Agencement': 'Anordnung',
    'Aménagement': 'Gestaltung',
    'Aménagement': 'Gestaltung',
    'Décoration': 'Dekoration',
    'Embellissement': 'Verschönerung',
    'Beauté': 'Schönheit',
    'Esthétique': 'Ästhetik',
    'Style': 'Stil',
    'Design': 'Design',
    'Modèle': 'Modell',
    'Patron': 'Muster',
    'Gabarit': 'Vorlage',
    'Format': 'Format',
    'Taille': 'Größe',
    'Dimension': 'Dimension',
    'Échelle': 'Maßstab',
    'Proportion': 'Proportion',
    'Rapport': 'Verhältnis',
    'Ratio': 'Verhältnis',
    'Pourcentage': 'Prozentsatz',
    'Taux': 'Rate',
    'Fréquence': 'Frequenz',
    'Occurrence': 'Vorkommen',
    'Incidence': 'Inzidenz',
    'Prévalence': 'Prävalenz',
    'Distribution': 'Verteilung',
    'Répartition': 'Verteilung',
    'Allocation': 'Zuweisung',
    'Attribution': 'Zuweisung',
    'Assignation': 'Zuweisung',
    'Répartition': 'Verteilung',
    'Partage': 'Teilung',
    'Division': 'Teilung',
    'Répartition': 'Verteilung',
    'Répartition': 'Verteilung',
    'Répartition': 'Verteilung',
    'Répartition': 'Verteilung'
  },
  'en': {
    // Traductions anglaises complètes ici...
    'Bienvenue': 'Welcome',
    'Accueil': 'Home',
    'Contact': 'Contact',
    'Services': 'Services',
    'À propos': 'About',
    'Connexion': 'Login',
    'Inscription': 'Register',
    'Rechercher': 'Search',
    'Menu': 'Menu',
    'Fermer': 'Close',
    'Ouvrir': 'Open',
    'Envoyer': 'Send',
    'Annuler': 'Cancel',
    'Valider': 'Validate',
    'Continental Bank': 'Continental Bank',
    'Continental Kreditbank': 'Continental Kreditbank',
    'EUROPA KREDIT BANK': 'EUROPA KREDIT BANK',
    'Banque': 'Bank',
    'Crédit': 'Credit',
    'Prêt': 'Loan',
    'Financement': 'Financing',
    'Solutions': 'Solutions',
    'Expertise': 'Expertise',
    'Relations': 'Relations',
    'Espace Client': 'Client Area',
    'Client Area': 'Client Area',
    'Presse': 'Press',
    'Carrières': 'Careers',
    'FAQ': 'FAQ',
    'Notre Institution': 'Our Institution',
    'Gouvernance': 'Governance',
    'Stratégie': 'Strategy',
    'Agréments Réglementaires': 'Regulatory Approvals',
    'Chiffres Clés': 'Key Figures',
    'Banque d\'Entreprises': 'Corporate Banking',
    'Gestion Patrimoine': 'Wealth Management',
    'Marchés Financiers': 'Financial Markets',
    'Produits de Crédit': 'Credit Products',
    'Simulateur de Prêt': 'Loan Calculator',
    'Recherche & Analyse': 'Research & Analysis',
    'Tableau de Bord': 'Dashboard',
    'Centre Conformité': 'Compliance Center',
    'Sécurité': 'Security',
    'Documents Légaux': 'Legal Documents',
    'Paris': 'Paris',
    'Téléphone': 'Phone',
    'Email': 'Email',
    'Adresse': 'Address',
    'Newsletter': 'Newsletter',
    'Suivez-nous': 'Follow us',
    'Mentions Légales': 'Legal Notice',
    'Conditions Générales': 'Terms & Conditions',
    'Politique Confidentialité': 'Privacy Policy',
    'Cookies': 'Cookies',
    'Droits Réservés': 'All Rights Reserved',
    'Excellence Bancaire Mondiale': 'Worldwide Banking Excellence',
    'Weltweite Bankexzellenz': 'Worldwide Banking Excellence',
    'Structurer l\'excellence financière': 'Structuring financial excellence',
    'pour les leaders mondiaux': 'for global leaders',
    'depuis': 'since',
    'Navigation': 'Navigation',
    'Institution': 'Institution',
    'Solutions': 'Solutions',
    'Expertise': 'Expertise',
    'Relations': 'Relations',
    'Financing': 'Financing',
    'Corporate Banking': 'Corporate Banking',
    'Wealth Management': 'Wealth Management',
    'Financial Markets': 'Financial Markets',
    'Credit Products': 'Credit Products',
    'Loan Calculator': 'Loan Calculator',
    'Research & Analysis': 'Research & Analysis',
    'Compliance Center': 'Compliance Center',
    'Legal Documents': 'Legal Documents',
    'Legal Notice': 'Legal Notice',
    'Terms & Conditions': 'Terms & Conditions',
    'Privacy Policy': 'Privacy Policy',
    'All Rights Reserved': 'All Rights Reserved',
    'Supervision Réglementaire': 'Regulatory Supervision',
    'Agrément ACPR': 'ACPR Approval',
    'Immatriculation REGAFI': 'REGAFI Registration',
    'ORIAS': 'ORIAS',
    'Membre du Fonds de Garantie': 'Member of the Guarantee Fund',
    'Garantie des dépôts': 'Deposit Guarantee',
    'jusqu\'à': 'up to',
    'Un crédit vous engage': 'A credit commits you',
    'doit être remboursé': 'must be repaid',
    'Vérifiez votre capacité': 'Check your capacity',
    'de remboursement': 'to repay',
    'avant de vous engager': 'before committing',
    'Siège social': 'Headquarters',
    'Avenue des Champs-Élysées': 'Avenue des Champs-Élysées',
    'RCS Paris': 'RCS Paris',
    'Capital social': 'Share capital',
    'SIRET': 'SIRET',
    'Informations Légales': 'Legal Information',
    'Support': 'Support',
    'Legal Notice': 'Legal Notice',
    'Banque agréée': 'Authorized bank',
    'par l\'Autorité': 'by the Authority',
    'de Contrôle Prudentiel': 'of Prudential Control',
    'et de Résolution': 'and Resolution',
    'Membre du Comité': 'Member of the Committee',
    'Consultatif du Secteur Financier': 'Consultative of the Financial Sector',
    'Financement Personnel': 'Personal Financing',
    'Nouvelle Construction': 'New Construction',
    'Logements Existants': 'Existing Homes',
    'Éducation': 'Education',
    'Création d\'Entreprise': 'Business Creation',
    'Financement Professionnel': 'Professional Financing',
    'Création': 'Creation',
    'Énergie': 'Energy',
    'Innovation': 'Innovation',
    'Financement Institutionnel': 'Institutional Financing',
    'Services Municipaux': 'Municipal Services',
    'International': 'International',
    'Financez vos projets personnels': 'Finance your personal projects',
    'POPULAIRE': 'POPULAR',
    'TAUX': 'RATE',
    'RAPIDE': 'FAST',
    'ÉTUDIANT': 'STUDENT',
    'AVENTURE': 'ADVENTURE',
    'Prêt Personnel': 'Personal Loan',
    'Prêt Immobilier': 'Home Loan',
    'Prêt Auto': 'Car Loan',
    'Prêt Éducation': 'Education Loan',
    'Prêt Voyage': 'Travel Loan',
    'Prêt Rénovation': 'Renovation Loan',
    'Taux fixe': 'Fixed rate',
    'Sans pénalité': 'No penalty',
    'Flexibilité totale': 'Total flexibility',
    'Assurance incluse': 'Insurance included',
    'Financement rapide': 'Fast financing',
    'Flexible': 'Flexible',
    'Taux compétitifs': 'Competitive rates',
    'Long terme': 'Long term',
    'Tous véhicules': 'All vehicles',
    'Taux attractifs': 'Attractive rates',
    'Paiements ajustables': 'Adjustable payments',
    'Travaux': 'Work',
    'Aide d\'urgence': 'Emergency help',
    'Soutien moral': 'Moral support',
    'Demander un prêt': 'Apply for a loan'
  },
  'nl': {
    // Traductions néerlandaises complètes ici...
    'Bienvenue': 'Welkom',
    'Accueil': 'Home',
    'Contact': 'Contact',
    'Services': 'Diensten',
    'À propos': 'Over ons',
    'Connexion': 'Inloggen',
    'Inscription': 'Registreren',
    'Rechercher': 'Zoeken',
    'Menu': 'Menu',
    'Fermer': 'Sluiten',
    'Ouvrir': 'Openen',
    'Envoyer': 'Verzenden',
    'Annuler': 'Annuleren',
    'Valider': 'Valideren',
    'Continental Bank': 'Continental Bank',
    'Continental Kreditbank': 'Continental Kreditbank',
    'EUROPA KREDIT BANK': 'EUROPA KREDIT BANK',
    'Banque': 'Bank',
    'Crédit': 'Krediet',
    'Prêt': 'Lening',
    'Financement': 'Financiering',
    'Solutions': 'Oplossingen',
    'Expertise': 'Expertise',
    'Relations': 'Relaties',
    'Espace Client': 'Klantenzone',
    'Client Area': 'Klantenzone',
    'Presse': 'Pers',
    'Carrières': 'Carrières',
    'FAQ': 'FAQ',
    'Notre Institution': 'Onze Instelling',
    'Gouvernance': 'Governance',
    'Stratégie': 'Strategie',
    'Agréments Réglementaires': 'Reglementaire Goedkeuringen',
    'Chiffres Clés': 'Kerncijfers',
    'Banque d\'Entreprises': 'Zakenbank',
    'Gestion Patrimoine': 'Vermogensbeheer',
    'Marchés Financiers': 'Financiële Markten',
    'Produits de Crédit': 'Kredietproducten',
    'Simulateur de Prêt': 'Lening Calculator',
    'Recherche & Analyse': 'Onderzoek & Analyse',
    'Tableau de Bord': 'Dashboard',
    'Centre Conformité': 'Compliance Center',
    'Sécurité': 'Veiligheid',
    'Documents Légaux': 'Juridische Documenten',
    'Paris': 'Parijs',
    'Téléphone': 'Telefoon',
    'Email': 'Email',
    'Adresse': 'Adres',
    'Newsletter': 'Nieuwsbrief',
    'Suivez-nous': 'Volg ons',
    'Mentions Légales': 'Juridische Kennisgeving',
    'Conditions Générales': 'Algemene Voorwaarden',
    'Politique Confidentialité': 'Privacybeleid',
    'Cookies': 'Cookies',
    'Droits Réservés': 'Alle Rechten Voorbehouden',
    'Excellence Bancaire Mondiale': 'Wereldwijde Bankexcellentie',
    'Weltweite Bankexzellenz': 'Wereldwijde Bankexcellentie',
    'Structurer l\'excellence financière': 'Financiële excellentie structureren',
    'pour les leaders mondiaux': 'voor wereldwijde leiders',
    'depuis': 'sinds',
    'Navigation': 'Navigatie',
    'Institution': 'Instelling',
    'Oplossingen': 'Oplossingen',
    'Expertise': 'Expertise',
    'Relaties': 'Relaties',
    'Financiering': 'Financiering',
    'Zakenbank': 'Zakenbank',
    'Vermogensbeheer': 'Vermogensbeheer',
    'Financiële Markten': 'Financiële Markten',
    'Kredietproducten': 'Kredietproducten',
    'Lening Calculator': 'Lening Calculator',
    'Onderzoek & Analyse': 'Onderzoek & Analyse',
    'Compliance Center': 'Compliance Center',
    'Juridische Documenten': 'Juridische Documenten',
    'Juridische Kennisgeving': 'Juridische Kennisgeving',
    'Algemene Voorwaarden': 'Algemene Voorwaarden',
    'Privacybeleid': 'Privacybeleid',
    'Alle Rechten Voorbehouden': 'Alle Rechten Voorbehouden'
  },
  'bg': {
    // Traductions bulgares complètes ici...
    'Bienvenue': 'Добре дошли',
    'Accueil': 'Начало',
    'Contact': 'Контакт',
    'Services': 'Услуги',
    'À propos': 'За нас',
    'Connexion': 'Вход',
    'Inscription': 'Регистрация',
    'Rechercher': 'Търсене',
    'Menu': 'Меню',
    'Fermer': 'Затвори',
    'Ouvrir': 'Отвори',
    'Envoyer': 'Изпрати',
    'Annuler': 'Отмени',
    'Valider': 'Потвърди',
    'Continental Bank': 'Continental Bank',
    'Continental Kreditbank': 'Continental Kreditbank',
    'EUROPA KREDIT BANK': 'EUROPA KREDIT BANK',
    'Banque': 'Банка',
    'Crédit': 'Кредит',
    'Prêt': 'Заем',
    'Financement': 'Финансиране',
    'Solutions': 'Решения',
    'Expertise': 'Експертиза',
    'Relations': 'Отношения',
    'Espace Client': 'Клиентска зона',
    'Client Area': 'Клиентска зона',
    'Presse': 'Преса',
    'Carrières': 'Кариери',
    'FAQ': 'ЧЗВ',
    'Notre Institution': 'Нашата институция',
    'Gouvernance': 'Управление',
    'Stratégie': 'Стратегия',
    'Agréments Réglementaires': 'Регулаторни одобрения',
    'Chiffres Clés': 'Ключови показатели',
    'Banque d\'Entreprises': 'Корпоративна банкова',
    'Gestion Patrimoine': 'Управление на активи',
    'Marchés Financiers': 'Финансови пазари',
    'Produits de Crédit': 'Кредитни продукти',
    'Simulateur de Prêt': 'Кредитен калкулатор',
    'Recherche & Analyse': 'Проучване и анализ',
    'Tableau de Bord': 'Табло за управление',
    'Centre Conformité': 'Център за съответствие',
    'Sécurité': 'Сигурност',
    'Documents Légaux': 'Правни документи',
    'Paris': 'Париж',
    'Téléphone': 'Телефон',
    'Email': 'Имейл',
    'Adresse': 'Адрес',
    'Newsletter': 'Бюлетин',
    'Suivez-nous': 'Последвайте ни',
    'Mentions Légales': 'Правна информация',
    'Conditions Générales': 'Общи условия',
    'Politique Confidentialité': 'Политика за поверителност',
    'Cookies': 'Бисквитки',
    'Droits Réservés': 'Всички права запазени',
    'Excellence Bancaire Mondiale': 'Световна банкова отличност',
    'Weltweite Bankexzellenz': 'Световна банкова отличност',
    'Structurer l\'excellence financière': 'Структуриране на финансова отличност',
    'pour les leaders mondiaux': 'за световни лидери',
    'depuis': 'от',
    'Navigation': 'Навигация',
    'Institution': 'Институция',
    'Решения': 'Решения',
    'Експертиза': 'Експертиза',
    'Отношения': 'Отношения',
    'Финансиране': 'Финансиране',
    'Корпоративна банкова': 'Корпоративна банкова',
    'Управление на активи': 'Управление на активи',
    'Финансови пазари': 'Финансови пазари',
    'Кредитни продукти': 'Кредитни продукти',
    'Кредитен калкулатор': 'Кредитен калкулатор',
    'Проучване и анализ': 'Проучване и анализ',
    'Център за съответствие': 'Център за съответствие',
    'Правни документи': 'Правни документи',
    'Правна информация': 'Правна информация',
    'Общи условия': 'Общи условия',
    'Политика за поверителност': 'Политика за поверителност',
    'Всички права запазени': 'Всички права запазени'
  }
};

// Générer une clé de traduction
function generateKey(text) {
  return text
    .toLowerCase()
    .replace(/[^\w\s]/g, '')
    .replace(/\s+/g, '_')
    .substring(0, 50)
    .replace(/_+$/, '');
}

// Générer les fichiers de traduction
function generateSmartTranslations() {
  console.log('🔍 Smart scan du projet pour extraire les textes pertinents...');
  
  const texts = smartScanProject();
  console.log(`✅ ${texts.length} textes pertinents trouvés`);

  // Créer le répertoire des locales s'il n'existe pas
  const localesDir = path.join(__dirname, '../locales');
  if (!fs.existsSync(localesDir)) {
    fs.mkdirSync(localesDir, { recursive: true });
  }

  // Générer le fichier français (textes originaux)
  const frTranslations = {};
  texts.forEach(text => {
    const key = generateKey(text);
    frTranslations[key] = text;
  });

  fs.writeFileSync(
    path.join(localesDir, 'fr.json'),
    JSON.stringify(frTranslations, null, 2),
    'utf8'
  );
  console.log('✅ Fichier fr.json généré');

  // Générer les autres fichiers de traduction
  const languages = ['de', 'en', 'nl', 'bg'];
  
  languages.forEach(lang => {
    const langTranslations = {};
    texts.forEach(text => {
      const key = generateKey(text);
      // Utiliser les traductions manuelles si disponibles, sinon le texte original
      langTranslations[key] = translations[lang]?.[text] || text;
    });

    fs.writeFileSync(
      path.join(localesDir, `${lang}.json`),
      JSON.stringify(langTranslations, null, 2),
      'utf8'
    );
    console.log(`✅ Fichier ${lang}.json généré`);
  });

  console.log('🎉 Tous les fichiers de traduction ont été générés avec qualité!');
  console.log(`📁 Localisation: ${localesDir}`);
  console.log(`📊 Statistiques: ${texts.length} textes traduits en 5 langues`);
}

// Exécuter le scan intelligent
if (require.main === module) {
  generateSmartTranslations();
}

module.exports = { smartScanProject, generateSmartTranslations, generateKey };
